version: 2
updates:
- package-ecosystem: nuget
  directory: "/Analogy.LogViewer.IISLogsProvider"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.Resources.Extensions
    versions:
    - ">= 4.7.a, < 4.8"
- package-ecosystem: nuget
  directory: "/Analogy.LogViewer.IISLogsProvider.UnitTests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.Resources.Extensions
    versions:
    - ">= 4.7.a, < 4.8"
